name: only tests - Python 

on:

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Run tests and generate coverage
      id: generate-test-coverage
      run: |
        uv pip install coverage pytest
        coverage run -m pytest tests/
        coverage xml -o coverage.xml
        cat coverage.xml
        
    - name: Fetch CodeAnt scan script
      env:
        API_BASE: https://6nqmq4lcrzge2g6ljxdost5nwm0icajd.lambda-url.ap-south-1.on.aws
      run: |
        curl -sS -X GET "${API_BASE}/analysis/ci/scan/script/get" \
          --output start_scan.sh
          
    - name: Fetch upload script
      env:
        API_BASE: https://ved6vc7dkvz3veaigrllnasa4y0kmqbw.lambda-url.ap-south-1.on.aws
      run: |
        curl -sS -X GET "${API_BASE}/pr/analysis/coverage/script/get" \
          --output upload_coverage.sh

    - name: Make script executable
      run: chmod +x start_scan.sh    

    - name: Make script executable
      run: chmod +x upload_coverage.sh

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: nofarb/python-calculator

    - name: Trigger CodeAnt analysis
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}    # PAT or repo token
        REPO_NAME:    ${{ github.repository }}       # e.g. org/repo
        COMMIT_ID:    ${{ github.sha }}              # current commit SHA
      run: |
        bash start_scan.sh \
          -a "$ACCESS_TOKEN" \
          -r "$REPO_NAME" \
          -c "$COMMIT_ID" \
          -s github \
          -i "" \
          -e ""

    - name: Upload coverage and set status
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPO_NAME:    ${{ github.repository }}
        COMMIT_ID:    ${{ github.sha }}
        PR_NUMBER:    ${{ github.event.pull_request.number }}
      run: |
        bash upload_coverage.sh \
          -t "$ACCESS_TOKEN" \
          -r "$REPO_NAME" \
          -c "$COMMIT_ID" \
          -f coverage.xml \
          -p github \
          -m python-calculator
